version: "3"

services:
  demo-container-mysq-db:
    image: mysql:8
    container_name: mysql
    #restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
    - "3306:3306"
    networks:
    - turreta_network
    
networks:
  turreta_network:
    driver: bridge